# Generated by Django 4.0.4 on 2022-04-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_delete_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
