# Generated by Django 4.0.4 on 2022-05-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_movie_image', models.ImageField(blank=True, null=True, upload_to='main_movie_image')),
                ('year_of_issue', models.DateField()),
                ('genre', models.CharField(choices=[('Драма/мелодрама', 'Драма/мелодрама'), ('Комедии', 'Комедии'), ('Фантастика', 'Фантастика'), ('Боевики', 'Боевики'), ('Мультфильмы', 'Мультфильмы'), ('Ужасы', 'Ужасы'), ('Документальные', 'Документальные')], default='Боевики', max_length=250)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('movie_trailer', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movie_image/')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_image', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Картинка фильма',
                'verbose_name_plural': 'Картинки фильмов',
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_comment', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
