# Generated by Django 4.0.4 on 2022-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
