# Generated by Django 4.0.4 on 2022-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Драма/мелодрама', 'Драма/мелодрама'), ('Комедии', 'Комедии'), ('Фантастика', 'Фантастика'), ('Боевики', 'Боевики'), ('Ужасы', 'Ужасы'), ('Мультфильмы', 'Мультфильмы')], default='Боевики', max_length=250),
        ),
    ]
