# Generated by Django 4.0.4 on 2022-05-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_ratingstar_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Драма/мелодрама', 'Драма/мелодрама'), ('Комедия', 'Комедия'), ('Фантастика', 'Фантастика'), ('Боевики', 'Боевики'), ('Ужасы', 'Ужасы'), ('Мультфильмы', 'Мультфильмы'), ('Аниме', 'Аниме'), ('Триллер', 'Триллер'), ('Детектив', 'Детектив'), ('Исторические', 'Исторические'), ('Документальные', 'Документальные'), ('Криминал', 'Криминал')], default='Боевики', max_length=250),
        ),
    ]
