# Generated by Django 4.0.4 on 2022-05-05 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='movie_image',
            field=models.FileField(null=True, upload_to='videos_trailers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
