# Generated by Django 4.0.4 on 2022-05-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
