# Generated by Django 4.0.4 on 2022-05-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='signature',
            new_name='image_about',
        ),
    ]
