# Generated by Django 4.0.4 on 2022-05-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_signature_about_image_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
